name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Backend
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
        cd /home/ubuntu/FileShare/backend
        git pull origin main
        source fshare/bin/activate
        pip install -r requirements.txt
        sudo systemctl restart flaskapp
        EOF

    - name: Deploy Frontend
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
        cd /home/ubuntu/FileShare/frontend
        git pull origin main
        npm install
        npm run build
        sudo systemctl restart nginx
        EOF
